GET http://127.0.0.1:25000/user
Accept: application/json
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFAbWFpbC5ydSIsInBhc3N3b3JkIjoiYSIsImV4cCI6MTY1ODY5NDgxMX0.ivXJQgLu57rs1p3DqqD9uc40ta-eY1UhTCpUAQHpP7g
###

PUT http://127.0.0.1:25000/user/password/
Accept: application/json
Content-Type: application/json
A: {}
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRhdmlkQG1haWwucnUiLCJwYXNzd29yZCI6InRlc3QyIiwiZXhwIjoxNjU4Njk0MTk3fQ.zcKgtjNpU6w2C486te7zfemqBCH2ZoPLTmdbd8MJjQU
###

DELETE http://127.0.0.1:25000/user/2
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRhdmlkQG1haWwucnUiLCJwYXNzd29yZCI6IjJoL0FDbEh1REdxdW5wR0JBRnlESXRsREttQzZjNkpSQXpUZWxKZmZVTlk9IiwiZXhwIjoxNjU3NjUyMjI1fQ.A6in9MOAM52kfCXp8x-J0y2x4LgQQTT7BgHnsXn4cvk

###


