POST http://127.0.0.1:25000/auth/login
Content-Type: application/json

{
  "email": "a@mail.ru",
  "password": "testtest"
}

###

POST http://127.0.0.1:25000/auth/register
Accept: application/json
Content-Type: application/json

{
  "email": "a@mail.ru",
  "password": "a"
}

###

PUT http://127.0.0.1:25000/auth/login/
Content-Type: application/json
Accept: application/json
Cookie: RefreshToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFybWVuQG1haWwucnUiLCJwYXNzd29yZCI6IjJoL0FDbEh1REdxdW5wR0JBRnlESXRsREttQzZjNkpSQXpUZWxKZmZVTlk9IiwiZXhwIjoxNjY5MTk0Njc0fQ.w17QZBEFoyGWu_GTgcc41e6AJBav0dEG0yJd_rO7zZw

{
  "email": "david@mail.ru",
  "password": "test2"
}

###