POST http://127.0.0.1:5000/auth/
Content-Type: application/json

{
  "email": "Max@mail.ru",
  "password": "test"
}

###

POST http://127.0.0.1:5000/auth
Accept: application/json
Content-Type: application/json

{
  "email": "armen@mail.ru",
  "password": "@test@12345"
}

###

POST http://127.0.0.1:5000/auth/login/
Accept: application/json
Content-Type: application/json

{
  "email": "armen@mail.ru",
  "password": "@test@12345"
}

###